### ISSUE TITLE
Problem with running the example file

### ISSUE THREAD

**Issue by sylestiel** [vanheeringen-lab/anansnake#11]
@siebrenf @JGASmits 
Hi,
I'm encountering problems with running the example file.
The error reads as follows:

could not find 'rna_samples' in /Users/pediatrics/Desktop/R_projects/scANANSE/example/rna_samples.tsv
SystemExit in line 29 of /Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/rules/configuration.smk:
1
  File "/Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/Snakefile", line 4, in <module>
  File "/Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/rules/configuration.smk", line 29, in <module>

Can either of you help me get past this problem.

**Comment by JGASmits** [comment]
Hi Sylestiel,

The error seems to indicate that the file "/Users/pediatrics/Desktop/R_projects/scANANSE/example/rna_samples.tsv" does not exist? Or does not contain the propper samples. And if it does exist (and is generated by scANANSE), how does it look like?

If you try to run scANANSE the sample file should look something like this:

> sample	assembly	anansesnake
> Clustername_1	mm10	Clustername_1
> Clustername_2	mm10	Clustername_2
> ....etc...
> Clustername_X	mm10	Clustername_X
> average	mm10	average

If you instead try to run the example data from anansnake, i think you forget to specify the ananse example config file. 
(since it refers to a sample file in the scANANSE folder instead of the one that is provided by the anansnake package)

Greetings

 JGA Smits

**Comment by sylestiel** [comment]
Thank you! The dry run worked!
